apiVersion: v1
kind: ConfigMap
metadata:
  name: multi-tenant-kv-store-config
  labels:
    app: multi-tenant-kv-store
data:
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_DEBUG: "true"
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  REDIS_HOST: "redis"              
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  HUEY_REDIS_HOST: "redis"       
  HUEY_REDIS_PORT: "6379"
  HUEY_REDIS_DB: "1"
