apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'fastapi'
        static_configs:
          - targets: ['fastapi-service.default.svc.cluster.local:8000'] # Update with your service name
      - job_name: 'redis'
        static_configs:
          - targets: ['redis.default.svc.cluster.local:6379']
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus.default.svc.cluster.local:6379']

      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana.default.svc.cluster.local:6379']

      - job_name: "locust"
        static_configs:
          - targets: ["locust.default.svc.cluster.local:8089"]



