apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap 
  labels:
    app: redis-cluster
data:
  redis.conf: |-
    bind 0.0.0.0
    port 6379
    protected-mode no
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    appendfilename "appendonly.aof"
    dir /data
    cluster-enabled yes
    cluster-require-full-coverage no
